export const GET_MANGAS = 'GET_MANGAS';
export const GET_CURRENT_MANGA = 'GET_CURRENT_MANGA';
export const GET_MANGA_CHAPTERS = 'GET_MANGA_CHAPTERS';
export const GET_CHAPTER_CONTENT = 'GET_CHAPTER_CONTENT';
export const CHAPTER_CONTENT_LOADING = 'CHAPTER_CONTENT_LOADING';